### ISSUE TITLE
How to access and modify time range parameters in TradingView chart?

### ISSUE THREAD

**Issue by arthvdh-vkv** [tradingview/charting-library-tutorial#136]
I need to understand how to access and modify the `from` and `to` time range parameters in the TradingView payload. Specifically, I want to:

1. Access the current time range parameters when making data requests
2. Modify these parameters to fetch data for specific timeframes

### Context

I'm implementing data chunking to improve performance as my chart currently loads large datasets. I want to dynamically update the time range based on user navigation (scrolling/zooming).

### Question

Where in the library can I find or intercept these time range parameters? Any documentation or example showing how to handle this would be helpful.

**Comment by arthvdh-vkv** [comment]
Hi! 👋 still looking for some guidance on accessing and modifying the time range parameters in TradingView charts. Any help from the community would be awesome! 🙏

**Comment by romfrancois** [comment]
The library handles data slightly differently than you may assume. It's not necessarily a "what you see is going to be requested" as the library will infer that if you start moving around the chart to go back in time it may possibly request a bigger range to limit the number of requests and therefore display data more quickly.

Having that in mind, whenever the library requests data for a given range there's no way to change that range. The `from` and `to` are passed from the library to the datafeed through `getBars`. If the range is too big you may want to cache internally more data to speed up the process and satisfy the request. Otherwise you may have to play with the `nextTime` property.

Have a look at this [article](https://www.tradingview.com/charting-library-docs/latest/connecting_data/datafeed-api/required-methods#correct-amount-of-data).

**Comment by arthvdh-vkv** [comment]
Thanks for the Help! will try to implementing the caching solution. 😊!
